---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCxhJBDfBbzq9JepBArRlKDRfad5Gcfogfvv1+JlrTpIbcAtct+lM/NPrY4I6NpEzqFod3o5P0v2G/uhOJ0CeuILPInR2HInAtmmCswXH1pdNcekfptwwwFhwMG+kVMs5cxekXzxNijNzqvv0y21NWfJcjZ31RTua8qemPCMJScqT8dDciwh8sWkafKgyfxcZD/3mx1JZWbhA5FnSMMkEEKsdBX11caP/7He7mDb0+dV8/vRv/5lS6DP6HIsVbsWBnBmu5u+M6MuY8Dyb2dpeDQBzebvZftSG5J1SBOtYM//RZcSDNgC/JVlvEWtaTwVirPnT5GDjJPOoSeXjsb+Sg8aP7HjCkgjAQ0RBVnB+caObxJYrTGsM+icNv1aXorxJFZ/yWWak/KgPurCSRmHXB/jDrb+yalN4SwJFV9CuhY/jEusnpNtTDaBGGwKeAcj06yifdGGLh+9SbgwZrddnpUDC5lMQIAZ+slYLcSYOhdVvHPQKvtGfdNjtzYrtJt2RL8fPEfl+a1ypfuyOhAdbneu82eV3EwpojvHRSNCpUMu4ZDqL2NkxVqHQJO6s7sBiFbGlCmGxrlgMN/AuYq3UwnVyjDWQpvaXwTOY6Mk5D3gmHbXiHKT4j7b/JcPG+QzL9PA+zVVe1ft647KkglRfEwVY2S5rkAkCgMN9UUGkeQy3ard2YIQEo9lnftMCQu6PBF1d8ep6/AFG7g8Ok36s2zUrRqEx/kzPOIVg==
    STRIPE_API_KEY: AgBT3BVxkZjDfe0BwQde9AGZtAF1XaVaNr/dSrjD1fcBiJJ42T0mmZnp9DcC6uijGx07ooVP3/5GtsysfLWiC2RjTzBGb4seSevTHeh6C/UGD9FVX7nYQZqPQ2OOTW1U+dXSQibqDDinF/rnfHrUpXoWD5D010zZnzHlczp0PwLzNN/vB6hQc/iavhgBqskncd8O/MIEqAZV3pAbKVOurye2luK8p8aYz/35BJ0EUXTWR/VL6xtIgMJaGcqPQVUV/nAm8g01p1uQQwHD2YEgvSDvXvnc6VnCUVQ1207fZlN8Q7gzITnsFJNDGDhD3UW8uIrkH/1JeYTwugstxGXEjz4xsB6LcE1FxcjCa6lEr3Z/a5DPKnaswflVM1iPV87nql3vcBHxsUV970G0wTHCSufP0qwVNcRaCucfSpeTEt45h4A69IlpNJc+e1eON6+D8nBzg/SolbGMZMC1wPxMS97wapgnR3bC1Q+ipgg2xA/tWcPjLPpYQ7gEBQgTaw/JneUq5kOZGdWClHT1cn2rDb+4wmQ6qe4/cKu7WWnhTkbHCx13uR9E/BbQ9LmjVD7x5mngBfmGljKyWWJMVXQPnjDFvyR4aHXqssBaed2IhyOuYtpVJHZxFv95dPlZ83geaKSCK+XZ4lFe+uqJZE9o2DC7SaHRWjpV2l3v+V/D+UhNY7JRcUarPJCx5Gms8bnoXjUrMlycajH2lXO0ihRnsQQ1DZKtBCM=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secret
      namespace: payments
    type: Opaque
